import { Stage, OnboardingStep, CohortConfig } from '@/types/onboarding';

export const COHORT_CONFIGS: CohortConfig[] = [
  {
    type: 'self-serve',
    label: 'Self-Serve',
    description: 'Automated purchase and self-serve guides',
    gtvRange: '<$500K',
    locationRange: '1-3',
    sellingPlan: 'Automated purchase',
    setupPlan: 'Self-serve guides + monitoring',
    color: 'bg-blue-500',
  },
  {
    type: 'assisted',
    label: 'Assisted',
    description: 'AE-guided with free IC support',
    gtvRange: '$500K-$2M',
    locationRange: '3-10',
    sellingPlan: 'AE-guided with self-checkout',
    setupPlan: 'Free IC support',
    color: 'bg-purple-500',
  },
  {
    type: 'managed',
    label: 'Managed',
    description: 'Full AE and paid implementation',
    gtvRange: '$2M+',
    locationRange: '10+',
    sellingPlan: 'AE negotiated pricing',
    setupPlan: 'Paid implementation package',
    color: 'bg-amber-500',
  },
];

export const STAGES: Stage[] = [
  {
    id: 'qualify-leads',
    title: 'Qualify Leads',
    description: 'Initial qualification and cohort assignment',
    steps: [1, 2, 3],
    color: 'bg-emerald-500',
  },
  {
    id: 'buying-experience',
    title: 'Buying Experience',
    description: 'Software and hardware selection',
    steps: [4, 5, 6],
    color: 'bg-blue-500',
  },
  {
    id: 'guided-setup',
    title: 'Guided Setup',
    description: 'KYC verification and final configuration',
    steps: [7, 8, 9, 10],
    color: 'bg-purple-500',
  },
];

export const ONBOARDING_STEPS: OnboardingStep[] = [
  // Stage 1: Qualify Leads
  {
    id: 1,
    title: 'Lead Capture',
    description: 'Initial interest form on marketing website',
    status: 'pending',
    stage: 'qualify-leads',
    dataCollected: [
      'Email address',
      'Business name',
      'Phone number (optional)',
      'Source/campaign tracking',
    ],
  },
  {
    id: 2,
    title: 'Account Creation & Profiling',
    description: 'Create account and collect qualifying information',
    status: 'pending',
    stage: 'qualify-leads',
    dataCollected: [
      'Full name',
      'Email (confirmed)',
      'Phone number',
      'Business category/vertical',
      'Annual revenue estimate',
      'Number of locations',
      'Current POS system',
      'Payment processing volume',
    ],
  },
  {
    id: 3,
    title: 'KYB Qualification',
    description: 'Business verification and risk assessment',
    status: 'pending',
    stage: 'qualify-leads',
    dataCollected: [
      'Business structure (LLC, Corp, etc.)',
      'Legal business name',
      'EIN (Employer ID Number)',
      'Registered business address',
      'Business formation date',
      'Website URL',
      'Industry classification (MCC)',
    ],
  },
  // Stage 2: Buying Experience
  {
    id: 4,
    title: 'Software Selection',
    description: 'Choose X-Series plan and features',
    status: 'pending',
    stage: 'buying-experience',
    dataCollected: [
      'X-Series plan tier',
      'Add-on modules selected',
      'Number of registers',
      'Number of users',
      'Billing frequency (monthly/annual)',
    ],
  },
  {
    id: 5,
    title: 'Hardware Selection',
    description: 'Select POS hardware and accessories',
    status: 'pending',
    stage: 'buying-experience',
    dataCollected: [
      'Terminal models and quantities',
      'Receipt printers',
      'Cash drawers',
      'Barcode scanners',
      'Other accessories',
      'Shipping addresses per location',
    ],
  },
  {
    id: 6,
    title: 'Purchase & Payment',
    description: 'Complete order and process payment',
    status: 'pending',
    stage: 'buying-experience',
    dataCollected: [
      'Payment method',
      'Billing address',
      'Purchase order number (if applicable)',
      'Contract signature',
      'Order confirmation',
    ],
  },
  // Stage 3: Guided Setup
  {
    id: 7,
    title: 'KYC & Payments Activation',
    description: 'Identity verification and activate payments per location',
    status: 'pending',
    stage: 'guided-setup',
    dataCollected: [
      'Business representative details',
      'Owner information (name, SSN, DOB, address)',
      'Ownership percentages',
      'Identity document uploads',
      'Background check consent',
    ],
  },
  {
    id: 8,
    title: 'Data Import',
    description: 'Import products, customers, and historical data',
    status: 'pending',
    stage: 'guided-setup',
    dataCollected: [
      'Product catalog (CSV/API)',
      'Customer database',
      'Historical sales data',
      'Inventory levels',
      'Supplier information',
      'Employee/staff list',
    ],
  },
  {
    id: 9,
    title: 'Bank Account Connection',
    description: 'Link payout account and enable settlements',
    status: 'pending',
    stage: 'guided-setup',
    dataCollected: [
      'Bank name',
      'Account type (checking/savings)',
      'Routing number',
      'Account number',
      'Account verification (micro-deposits or instant)',
    ],
  },
  {
    id: 10,
    title: 'Hardware Setup & Go Live',
    description: 'Configure terminals and launch system',
    status: 'pending',
    stage: 'guided-setup',
    dataCollected: [
      'Terminal pairing confirmations',
      'Test transaction results',
      'Staff training completion',
      'Go-live checklist sign-off',
      'Support contact preferences',
    ],
  },
];
